require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  enabled: true
  Max: 40

Layout/LineLength:
  Enabled: true
  Max: 160

Metrics/AbcSize:
  Enabled: true
  Max: 30

Rails/BulkChangeTable:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 25

Rails/ReversibleMigration:
  Enabled: false
